// <auto-generated />
using DemoApp.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoApp.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210512074325_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoApp.DAL.Cities", b =>
                {
                    b.Property<string>("CityId")
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("CityName")
                        .HasColumnType("Varchar(50)");

                    b.Property<string>("CountryId")
                        .HasColumnType("Varchar(10)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("DemoApp.DAL.Countries", b =>
                {
                    b.Property<string>("CountryId")
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("CountryName")
                        .HasColumnType("Varchar(50)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("DemoApp.DAL.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("Contcat")
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("Varchar(10)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("Varchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("Varchar(25)");

                    b.Property<bool>("Terms")
                        .HasColumnType("Bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("Varchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
